services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"  # Map container's 3000 to Mac's 3000
    environment:
      - BACKEND_URL=http://localhost:8000
