version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    network_mode: host
    #ports:
    #  - "3000:80"
    environment:
      - BACKEND_URL=http://localhost:2000 # Set the backend URL dynamically here

